### PR TITLE
Add unbox vectors with sigil links instead

### PR DESCRIPTION
**Pull request by Powersource**
For https://github.com/ssbc/ssb-tribes/issues/102

Replacement for https://github.com/ssbc/private-group-spec/pull/35

### CODE REVIEW

**Comment by Powersource** [comment]
tests passing locally

**Comment by Powersource** [comment]
this is used in https://github.com/ssbc/ssb-box2/pull/35 now

**Review by mixmix — APPROVED** [review]
Good to go

**Comment by Powersource** [comment]
v8.1.0

**Pull request merged**
